version: '3.8'

# 定义全局日志策略
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    logging: *default-logging

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: always
    ports:
      - "127.0.0.1:4321:4321"
    logging: *default-logging